### ISSUE TITLE
Invite acceptance fails to propagate to the SS client

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/sliding-sync#35] opened 2022-08-15 15:05 UTC
**Describe the bug**
I logged into the ss web client and was presented with a series of unaccepted invites, all invites are repeated once (so 2 invites in the client for each real invite). In all cases, I have previously accepted invites to these rooms.

I _think_ it is true to say that in all cases, the invite was sent and accepted in the period between SS logins. 

**To Reproduce**
Close down SS client, send invite to my user, accept invite in a regular client, reopen SS client.

**Expected behavior**
Invite acceptance should propagate.

All room ids are for private rooms, so I will send them out of band.

**Comment by kegsay** [comment] 2022-08-16 13:52
Unable to reproduce this locally / in E2E tests. I hypothesise that the `UserCache` was corrupted somehow. This bug was reproducible on a fresh `ConnState`: indicating DB or in-memory corruption. Manually checking the DB showed the invites table still had entries for these rooms. Each room was duplicated exactly once, which is possible in `ConnState` if the room is both in the joined room list _and_ the invited room list, as we don't de-dupe on room ID.

**Comment by kegsay** [comment] 2022-08-17 11:39
I believe this was fixed in https://github.com/matrix-org/sliding-sync/commit/306b720ebe93a745b3b6a8fddfdad93c2c5e3e8f - please open a new issue if you see this again.

**Closed by kegsay** 2022-08-17 11:39 UTC
Labels: bug, major
