### ISSUE TITLE
Initial sync is worryingly slow & big to get to clients.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#16] opened 2022-12-28 00:49 UTC
While chasing down https://github.com/matrix-org/matrix-rust-sdk/issues/1308 i was seeing initial sync reqs taking 36s to arrive. This was in part exasperated by the req having a 10s timeout on it, but even after fixing that, things are taking a worryingly long time - especially after ~12h of being offline. 

Here's one i just profiled taking ~5s to execute (after ~2h of being offline). Client saw:

```
2022-12-28T00:21:59.635174Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some(10), filters: None }], room_subscriptions: {}, unsubscribe_rooms: [], extensions: ExtensionsConfig { to_device: Some(ToDeviceConfig { enabled: Some(true), limit: None, since: None }), e2ee: Some(E2EEConfig { enabled: Some(true) }), account_data: Some(AccountDataConfig { enabled: Some(true) }), other: {} } } config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver=Some("https://slidingsync.lab.element.dev/")}:send{config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver="https://slidingsync.lab.element.dev/" user_id=Some("@matthew:matrix.org") server_versions=[V1_0, V1_1, V1_2, V1_3, V1_4, V1_5] request_type="ruma_client_api::sync::sync_events::v4::Request"}: matrix_sdk::http_client: Sending request
2022-12-28T00:22:04.412702Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some(10), filters: None }], room_subscriptions: {}, unsubscribe_rooms: [], extensions: ExtensionsConfig { to_device: Some(ToDeviceConfig { enabled: Some(true), limit: None, since: None }), e2ee: Some(E2EEConfig { enabled: Some(true) }), account_data: Some(AccountDataConfig { enabled: Some(true) }), other: {} } } config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver=Some("https://slidingsync.lab.element.dev/")}:send{config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver="https://slidingsync.lab.element.dev/" user_id=Some("@matthew:matrix.org") server_versions=[V1_0, V1_1, V1_2, V1_3, V1_4, V1_5] request_type="ruma_client_api::sync::sync_events::v4::Request"}: matrix_sdk::http_client: Got response: Response { status: 200, version: HTTP/1.1, headers: {"access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, Authorization", "access-control-allow-methods": "GET, POST, PUT, DELETE, OPTIONS", "access-control-allow-origin": "*", "content-type": "application/json", "date": "Wed, 28 Dec 2022 00:22:01 GMT", "transfer-encoding": "chunked", "set-cookie": "......; path=/; HttpOnly; Secure; SameSite=None"}, body: b"{\"lists\":[{\"ops\":[{\"op\":\"SYNC\",\"range\":[0,20],
```

Server saw:

```
00:22:00 INF created new connection conn_id=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 user=@matthew:matrix.org
00:22:01 WRN Client did not increment since token: possibly sending back duplicate to-device events! device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 initial=true last_sent=6950241 recv=0 user=@matthew:matrix.org
00:22:01 INF  ag=25 d=1 duration=1111.414264 p=0 q=1 r=21 size=296993 status=200 u=@matthew:matrix.org
00:22:04 INF  dl-c=71 dl-l=8 duration=32.985866 p=1 q=2 r=0 size=2200 status=200 u=@matthew:matrix.org
00:22:05 INF  duration=44.822427 p=2 q=3 r=0 size=327 status=200 u=@matthew:matrix.org
```

Server pprof saw (for the OnIncomingRequestInitial):

```
When	Elapsed	Goroutine ID	Events
4.451185334s	1.105535526s		Task 1964 (goroutine view) (complete)
4.451185334	 .         	39366	task OnIncomingRequestInitial (id 1964, parent 0) created
4.451192886	 .     7552	39366	region load started (duration: 42.257935ms)
4.493469125	 . 42276239	39366	region onIncomingListRequest started (duration: 32.959255ms)
4.526486083	 . 33016958	39366	region buildRooms started (duration: 1.000488985s)
4.558728129	 . 32242046	39366	new goroutine 39367: database/sql.(*DB).beginDC·dwrap·17
4.560168230	 .  1440101	39366	new goroutine 39395: database/sql.(*Rows).initContextClose·dwrap·27
4.562780862	 .  2612632	39366	region RoomStateAfterEventPosition started (duration: 941.937482ms)
4.563280573	 .   499711	39366	new goroutine 39294: database/sql.(*DB).beginDC·dwrap·17
4.568830597	 .  5550024	39366	new goroutine 39368: database/sql.(*Rows).initContextClose·dwrap·27
4.570190699	 .  1360102	39366	new goroutine 39369: database/sql.(*Rows).initContextClose·dwrap·27
5.527456348	 .957265649	39366	region extensions started (duration: 29.246106ms)
5.549077859	 . 21621511	39366	new goroutine 39295: database/sql.(*DB).beginDC·dwrap·17
5.551339387	 .  2261528	39366	new goroutine 39296: database/sql.(*DB).beginDC·dwrap·17
5.552959072	 .  1619685	39366	new goroutine 39396: database/sql.(*Rows).initContextClose·dwrap·27
5.553884664	 .   925592	39366	new goroutine 39297: database/sql.(*DB).beginDC·dwrap·17
5.555373534	 .  1488870	39366	new goroutine 39373: database/sql.(*Rows).initContextClose·dwrap·27
5.556710390	 .  1336856	39366	region liveUpdate started (duration: 6.246µs)
5.556720860	 .    10470	39366	task end
```

So: if it took 1111ms to generate on the server (which is already quite a lot; the 300KB request size is *way* too large thanks to including 130KB of redundant account_data on it, and 20*20 = 400 events of scrollback), how come it took the client another 3s to receive it? I guess this could be slow internet connectivity whilst travelling for xmas, but empirically i seem to be able to download stuff at ~4MB/s.

To address the size, i think account_data has to be incremental, as per https://github.com/matrix-org/matrix-spec-proposals/pull/3575/files#r1057933023 - and we should always avoid syncing in scrollback in rooms during initial sync. However, it doesn't explain whey the request took 1s to execute but blocked the client for 5s...

**Comment by ara4n** [comment] 2022-12-28 11:07
Here's another one, this time after 10h of downtime:

New run after being offline for ~10h:

Clientside:
```
2022-12-28T11:00:44.594228Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some(10), filters: None }], room_subscriptions: {}, unsubscribe_rooms: [], extensions: ExtensionsConfig { to_device: Some(ToDeviceConfig { enabled: Some(true), limit: None, since: None }), e2ee: Some(E2EEConfig { enabled: Some(true) }), account_data: Some(AccountDataConfig { enabled: Some(true) }), other: {} } } config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver=Some("https://slidingsync.lab.element.dev/")}:send{config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver="https://slidingsync.lab.element.dev/" user_id=Some("@matthew:matrix.org") server_versions=[V1_0, V1_1, V1_2, V1_3, V1_4, V1_5] request_type="ruma_client_api::sync::sync_events::v4::Request"}: matrix_sdk::http_client: Serializing request
2022-12-28T11:00:44.594372Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some(10), filters: None }], room_subscriptions: {}, unsubscribe_rooms: [], extensions: ExtensionsConfig { to_device: Some(ToDeviceConfig { enabled: Some(true), limit: None, since: None }), e2ee: Some(E2EEConfig { enabled: Some(true) }), account_data: Some(AccountDataConfig { enabled: Some(true) }), other: {} } } config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver=Some("https://slidingsync.lab.element.dev/")}:send{config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver="https://slidingsync.lab.element.dev/" user_id=Some("@matthew:matrix.org") server_versions=[V1_0, V1_1, V1_2, V1_3, V1_4, V1_5] request_type="ruma_client_api::sync::sync_events::v4::Request"}: matrix_sdk::http_client: Sending request
2022-12-28T11:00:51.699526Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some(10), filters: None }], room_subscriptions: {}, unsubscribe_rooms: [], extensions: ExtensionsConfig { to_device: Some(ToDeviceConfig { enabled: Some(true), limit: None, since: None }), e2ee: Some(E2EEConfig { enabled: Some(true) }), account_data: Some(AccountDataConfig { enabled: Some(true) }), other: {} } } config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver=Some("https://slidingsync.lab.element.dev/")}:send{config=Some(RequestConfig { timeout: 60s, retry_limit: None, retry_timeout: None }) homeserver="https://slidingsync.lab.element.dev/" user_id=Some("@matthew:matrix.org") server_versions=[V1_0, V1_1, V1_2, V1_3, V1_4, V1_5] request_type="ruma_client_api::sync::sync_events::v4::Request"}: matrix_sdk::http_client: Got response: Response { status: 200, version: HTTP/1.1, headers: {"access-control-allow-headers": "Origin, X-Requested-With, Content-Type, Accept, Authorization", "access-control-allow-methods": "GET, POST, PUT, DELETE, OPTIONS", "access-control-allow-origin": "*", "content-type": "application/json", "date": "Wed, 28 Dec 2022 11:00:50 GMT", "transfer-encoding": "chunked", "set-cookie": ".........; path=/; HttpOnly; Secure; SameSite=None"}, body: b"{\"lists\":[{\"ops\":[{\"op\":\"SYNC\",\"range\":[0,20],
```

Serverside:
```
11:00:45 INF created new connection conn_id=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 user=@matthew:matrix.org
11:00:46 WRN Client did not increment since token: possibly sending back duplicate to-device events! device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 initial=true last_sent=6956510 recv=0 user=@matthew:matrix.org
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=FAF1AFEB-E0DE-4A1C-8EFE-9A725BFCA605
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=76fa1180-a2ce-4e9b-a384-adffc4bed0d5
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=a6cf24b4-b675-457c-861e-4700fa7ae7fa
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=a8206e85-a317-464b-bba3-79954af724c0
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=fc927ff3-ca16-4a47-a8df-e561249fd674
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=d994ca53-f687-4f8b-8da7-d2db345cfda9
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=164d818f-a404-4128-bf8a-239ac1a24479
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=fbfc3a92-3fe0-4e93-bcdb-eed23251306e
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=e4583817-f443-43cb-bc4d-540cf2e4f126
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=F6F1C103-752C-46A1-929F-91D29F0B22B9
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=be463522-0df9-4dac-a1a9-0f0d05a40d66
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=df7f0af8-01af-4ee4-ba32-dfc38ae2cd45
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=2090c94c-db68-40b5-8de9-bdd983af8d55
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=f80e2966-6b9d-49e9-99fc-dc677c9e3d27
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=2df9b15e-96bb-4c03-a220-caebc8e2f5ca
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=7c91959e-6f36-4848-8b6f-6dfaaef6f70b
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=ed9f0404-5f8c-421a-8fba-f48322514302
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=8b52098a-0879-4cc0-acf2-146310b2e5a3
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=91d299b5-74a3-4523-9ef8-97815a7be201
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=685c4b34-266d-4b60-9a33-7e47eba16a27
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=94AC7AC8-DE15-4600-8D98-BE62F1DC77EE
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=34d62e4a-9847-4dcb-8873-d39805dcddaa
11:00:50 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=878c0399-6d6d-4899-9dc8-2c08e7d4a654
11:00:50 INF  ag=25 d=23 duration=5070.082967 p=0 q=1 r=21 size=399763 status=200 u=@matthew:matrix.org
11:00:52 INF  dl-c=352 dl-l=35 duration=66.935369 p=1 q=2 r=0 size=10312 status=200 u=@matthew:matrix.org
11:00:52 INF  duration=71.452315 p=2 q=3 r=1 size=846 status=200 u=@matthew:matrix.org
11:00:56 INF  duration=3389.829977 p=3 q=4 r=0 size=313 status=200 u=@matthew:matrix.org
11:00:57 INF  duration=36.677605 p=4 q=5 r=1 size=717 status=200 u=@matthew:matrix.org
11:01:05 INF  duration=7519.056685 p=5 q=6 r=1 size=908 status=200 u=@matthew:matrix.org
11:01:05 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=F0BAA31D-3315-4ED6-B005-04C122DD8558
11:01:05 INF  d=1 duration=33.431959 p=6 q=7 r=0 size=366 status=200 u=@matthew:matrix.org
11:01:06 INF  duration=39.089825 p=7 q=8 r=1 size=808 status=200 u=@matthew:matrix.org
```

Pprof of 5s OnIncomingRequestInitial:

```
When	Elapsed	Goroutine ID	Events
6.081120159s	5.063043811s		Task 2559 (goroutine view) (complete)
6.081120159	 .         	46984	task OnIncomingRequestInitial (id 2559, parent 0) created
6.081129222	 .     9063	46984	region load started (duration: 693.533809ms)
6.774674218	 .693544996	46984	region onIncomingListRequest started (duration: 28.299495ms)
6.803026782	 . 28352564	46984	region buildRooms started (duration: 631.54459ms)
6.852989439	 . 49962657	46984	new goroutine 46986: database/sql.(*DB).beginDC·dwrap·17
6.855811658	 .  2822219	46984	new goroutine 46971: database/sql.(*Rows).initContextClose·dwrap·27
6.858783687	 .  2972029	46984	region RoomStateAfterEventPosition started (duration: 551.195066ms)
6.859238189	 .   454502	46984	new goroutine 46987: database/sql.(*DB).beginDC·dwrap·17
6.862468574	 .  3230385	46984	new goroutine 46972: database/sql.(*Rows).initContextClose·dwrap·27
6.863682627	 .  1214053	46984	new goroutine 46973: database/sql.(*Rows).initContextClose·dwrap·27
7.435256453	 .571573826	46984	region extensions started (duration: 3.708890621s)
11.120415767	3.685159314	46984	new goroutine 46988: database/sql.(*DB).beginDC·dwrap·17
11.123099899	 .  2684132	46984	new goroutine 46996: database/sql.(*DB).beginDC·dwrap·17
11.134975984	 . 11876085	46984	new goroutine 46997: database/sql.(*Rows).initContextClose·dwrap·27
11.136070844	 .  1094860	46984	new goroutine 46977: database/sql.(*DB).beginDC·dwrap·17
11.141054725	 .  4983881	46984	new goroutine 46998: database/sql.(*Rows).initContextClose·dwrap·27
11.144153909	 .  3099184	46984	region liveUpdate started (duration: 5.683µs)
11.144163970	 .    10061	46984	task end
GC:0s
```

So, 5s to generate a response on the server, resulting in a 7s delay on the client.

**Comment by kegsay** [comment] 2022-12-29 10:28
`region extensions started (duration: 3.708890621s)` probably device events

**Comment by kegsay** [comment] 2022-12-29 10:31
We may be reaching database limits at this point, given how sporadic the load times are (42 or 693ms to `region load` load the room list is suspicious)

**Comment by ara4n** [comment] 2022-12-30 10:51
> `region extensions started (duration: 3.708890621s)` probably device events

but there's only ~22 to-device events?

**Comment by kegsay** [comment] 2022-12-30 14:59
Yes but it needs to query a to device events table that was at last check 7 million rows.

**Comment by ara4n** [comment] 2022-12-31 11:44
Here's another excruciating 37s one:

```
2022-12-31T10:00:28.495451Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some>
2022-12-31T10:00:28.496058Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some>
2022-12-31T10:01:06.848306Z TRACE send_inner{request=Request { pos: None, txn_id: None, timeout: Some(30s), lists: [SyncRequestList { slow_get_all_rooms: false, ranges: [(0, 20)], sort: ["by_recency", "by_name"], required_state: [(RoomAvatar, ""), (RoomEncryption, "")], timeline_limit: Some>
```

and

```
10:00:28 INF created new connection conn_id=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 user=@matthew:matrix.org
10:00:29 WRN Client did not increment since token: possibly sending back duplicate to-device events! device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 initial=true last_sent=7250544 recv=0 user=@matthew:matrix.org
10:01:06 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=6a890877-9f58-4f5f-8414-62c5fbbc0974
10:01:06 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=b52d1413-7266-40ec-b020-ed1df9a42224
10:01:06 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=95d500b8-d8a9-4b48-8b28-ee4aa48062e4
10:01:06 INF ToDeviceTable.Messages device=ec725749c89702fe5e1fc5e019e77ce22dc0f3ae0717483f307a02e2222c6631 msgid=7bd978c0-f431-47f0-aeb3-625a0f4f367b
10:01:06 INF  ag=25 d=4 dl-c=1 duration=37591.21913 p=0 q=1 r=21 size=347050 status=200 u=@matthew:matrix.org
```

Presumably to fix this:
 * We need to actually delete the to-device messages to the device which the device has acknowledged receiving(!)
 * Or we could at least slap an index on the db. 7m rows is nothing.

**Comment by kegsay** [comment] 2023-01-04 16:47
> We need to actually delete the to-device messages to the device which the device has acknowledged receiving(!)

We've always done this.

> Or we could at least slap an index on the db. 7m rows is nothing.

We have indexes.

After much analysis, the conclusions:
 - add another index for position, device_id - this was done in https://github.com/matrix-org/sliding-sync/commit/f47e71c726839ae94d068bc6aadbf4e1e19ae3f8
 - Make sure clients (EX) persist the `next_batch` token between sessions. If you keep sending up `since=0` then postgres has to scan a lot more data than is required, adding ~500ms to the _average_ timings.

The very slow 37s one was also caused by the to-device table, but it's hard to know if these conclusions will be enough to resolve them. Clearing out the to-device table of stale msgs (deleted devices, etc) would also help constrain growth.

**Comment by kegsay** [comment] 2023-01-13 18:22
Closing this as we have done many performance improvements for the initial sync:
 - `region RoomStateAfterEventPosition` now takes <100ms, as opposed to 500-1000ms. https://github.com/matrix-org/sliding-sync/commit/00e4b8238ce144054d93ab75a43785f63674990b
 - `region extensions` now has a better to_device index. https://github.com/matrix-org/sliding-sync/commit/f47e71c726839ae94d068bc6aadbf4e1e19ae3f8

Further gains can be made (thanks Stefan!) by:
 - Batching up `TransactionIDForEvents` to be a single query for all returned rooms, currently it's one query per room.
 - Batching up `SelectClosestPrevBatchByID` to be a single query for all returned rooms, currently it's one query per room.

This will save 50-100ms more.

**Closed by kegsay** 2023-01-13 18:22 UTC
Labels: performance
