### ISSUE TITLE
Events sent over `/sendToDevice` never arrive

### ISSUE THREAD

**Issue by poljar** [matrix-org/sliding-sync#53] opened 2022-10-18 16:16 UTC
The sliding sync proxy seems to have support for to-device messaging via the extensions field in the sync response. Sadly that field never seems to contain an `events` field nor any events.

![image](https://user-images.githubusercontent.com/552026/196485149-7d026a4f-cee0-41d3-88df-f555807c992e.png)

The left side shows the capture of mitmproxy script that outpus the current `pos` and the `to_device` field of sync responses a client receives.

The right side shows how we're sending two `m.dummy` events to the server, once for the specific device that is using sliding sync, and once a wildcard is used to send the event to all devices. Neither event is received over sliding sync.

Element web received the `*` message just fine:

![image](https://user-images.githubusercontent.com/552026/196485552-790543bc-d339-436a-b975-3b796358abde.png)

For completeness, here's the `mitmproxy` script that was used to output the log in the left window:

```python
import json

from mitmproxy import http, ctx

log_file = open("/home/poljar/to-device.log", "wt")


def response(flow: http.HTTPFlow) -> None:
    if flow.request.path.startswith("/_matrix/client/unstable/org.matrix.msc3575/sync"):
        if flow.response.status_code == 200:
            try:
                body = json.loads(flow.response.content)

                to_device = body["extensions"]["to_device"]
                pos = body["pos"]

                line = f"Received a sync response pos {pos}, to-device field {to_device}"

                ctx.log(line)
                log_file.writelines(line + '\n')
                log_file.flush()

            except KeyError as e:
                ctx.log(f"Error finding to-device {e}")
```

**Comment by gnunicorn** [comment] 2022-10-21 11:54
running the latest sliding-sync proxy locally, I can see we receive to-device events (with jack-in the matrix testing client), but not over ROSA... I can confirm this seems to be a problem on the public setup.

**Comment by kegsay** [comment] 2022-10-24 10:21
Are you using different access tokens when testing? If you reuse the access token the proxy is using in say Element-Web then you may end up not seeing to-device messages as they will be racing with each other.

**Comment by gnunicorn** [comment] 2022-10-24 10:22
> Are you using different access tokens when testing?

jack-in has its own login now, so they are separate access tokens now.

**Comment by kegsay** [comment] 2022-10-24 10:24
Have you tried logging out the access token used in the proxy and then logging in again with a fresh access token? I did play around with the database a few days ago when updating versions so it's possible that the device in question isn't polling.

**Comment by kegsay** [comment] 2022-10-24 10:24
Whoops, failed to clicked comment :/

**Comment by poljar** [comment] 2022-10-24 10:29
> Have you tried logging out the access token used in the proxy and then logging in again with a fresh access token? I did play around with the database a few days ago when updating versions so it's possible that the device in question isn't polling.

Tests were made with a fresh, never used access token. E2EE won't work with access tokens that Element has used.

**Comment by kegsay** [comment] 2022-10-24 10:34
Can you please:
 - test it again, and let me know the timestamps (UTC).
 - Include the output of https://slidingsync.lab.element.dev/client/server.json from when you did the test.

Follow up Qs:
 - Is this 100% reproducible? It sounds like it is? As in, no to-device messages get to the client at _all_.
 - Exactly what is your `/sendToDevice` request? I'll need this to add a regression test.

**Comment by poljar** [comment] 2022-10-24 10:45
> Can you please:

Sure.

> Follow up Qs:
> 
> Is this 100% reproducible? It sounds like it is? As in, no to-device messages get to the client at _all_.

Correct, I tried this out some 3-5 times, every time the same behavior was observed. I don't see any traffic arriving over to-device at all, I left it on for an hour and no traffic ever arrived. The token never changes either.

> Exactly what is your `/sendToDevice` request? I'll need this to add a regression test.

Well I tried this in combination with Element first, which sent `m.room.encrypted` events that seemingly don't arrive. After being confused I confirmed my suspicion that E2EE is broken because to-device traffic isn't arriving. I tried to send `m.dummy` events like it's shown in the above pictures using the following command line:

```bash
https -A bearer -a "$ACCESS_TOKEN" PUT https://matrix.org/_matrix/client/v3/sendToDevice/m.dummy/"$(shuf -i 1-100000000 -n 1)" messages:='{"@poljar:matrix.org": { "*": {} } }'
```

`https` is httpie: https://github.com/httpie/httpie. I used the access token from Element for the command, but that should hardly matter since I'm using a wildcard recipient as the device anyways.

**Comment by kegsay** [comment] 2022-10-24 10:57
Few more Qs:

- when you say it works locally, what is running locally? Just the proxy or a proxy and a local synapse?
- if you do an initial (no ?pos request), do those messages arrive?

**Comment by gnunicorn** [comment] 2022-10-24 11:25
> when you say it works locally, what is running locally? Just the proxy or a proxy and a local synapse?

proxy only, against matrix.org

> What proxy version is shown at startup?

```
sliding-sync-sliding-sync-1  | Sync v3 [0.5.2] (37d3937f9502cc635bf37da3e968c054c58d5257)
sliding-sync-sliding-sync-1  | 11:13:07 INF creating handler
sliding-sync-sliding-sync-1  | 11:13:13 INF retrieved global snapshot from database
sliding-sync-sliding-sync-1  | 11:13:13 INF listening on 0.0.0.0:8008
sliding-sync-sliding-sync-1  | 11:13:13 INF StartV2Pollers num_devices=2
```

> if you do an initial (no ?pos request), do those messages arrive?

To, clarify you mean: the proxy is running, to-device is sent, the sliding-sync client is starting and fetching initially? Do they arrive? No.

```

sliding-sync-sliding-sync-1  | 11:16:19 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:21 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:21 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:23 INF created new connection conn_id=5825900661df909b469444168e23c413a41de4384b584155123800a0a0e62fd9 user=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:24 INF  ag=18 d=1 duration=986.932024 p=0 q=1 r=21 size=158482 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:24 INF  duration=376.807044 p=1 q=2 r=20 size=143638 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:25 INF  duration=87.620768 p=2 q=3 r=20 size=148315 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:25 INF  duration=579.47338 p=3 q=4 r=20 size=140547 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:26 INF  duration=193.19893 p=4 q=5 r=20 size=43922 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:26 INF  duration=169.465957 p=5 q=6 r=20 size=24934 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:26 INF  duration=157.550752 p=6 q=7 r=20 size=23771 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:26 INF  duration=103.35003 p=7 q=8 r=9 size=9172 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:27 INF  duration=812.212366 p=8 q=9 r=140 size=665884 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:32 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:35 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:35 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:36 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:36 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:37 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,1,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:39 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:46 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:46 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:47 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:47 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:48 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,1,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:50 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:50 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:52 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:54 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:57 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:16:57 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:00 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:00 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:02 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:03 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:03 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,1,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:04 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:05 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:10 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:10 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:11 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:11 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:14 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:17 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:17 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:18 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:19 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:20 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:21 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,1,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:22 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:22 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:24 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:27 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:27 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:28 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:17:29 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org

```


The only scenario that works for me locally:

1. have proxy running
2. start sliding sync (jack-in), waiting for sync
3. send https as described above to synapse
4. await in sliding sync to tell me:
```
 │13:18:23:TRACE:matrix_sdk_base::sliding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:48:1 ToDevice Events found                                │
```

Regardless of that, the proxy never shows any log with `to_device=1` ...

---

building latest `git main` now:
```
sliding-sync-sliding-sync-1  | Sync v3 [0.5.2] (37d3937f9502cc635bf37da3e968c054c58d5257)
sliding-sync-sliding-sync-1  | 11:21:48 INF creating handler
sliding-sync-sliding-sync-1  | 11:21:52 INF retrieved global snapshot from database
sliding-sync-sliding-sync-1  | 11:21:52 INF listening on 0.0.0.0:8008
sliding-sync-sliding-sync-1  | 11:21:52 INF StartV2Pollers num_devices=2
```

Seems to be identical: Nothing at startup (or it runs by too fast, inline logs) but I see it if I trigger it via `https`. 

Switching to ROSA: no `1 ToDevice` in my jack-in logs :( .

**Comment by kegsay** [comment] 2022-10-24 11:34
> To, clarify you mean: the proxy is running, to-device is sent, the sliding-sync client is starting and fetching initially? Do they arrive? No.

So there's 3 scenairos I'm interested in:

Initial login:
- /login with a new device ID
- On another account send to-device to this device ID.
- Hit proxy for the first time (login) -> do you get it? Sounds like no.

Polling:
- /login with a new device ID
- Hit proxy for first time (login) - begin polling.
- Send to-device -> do you get it? Sounds like yes locally only.

Initial proxy connection:
- /login with a new device ID
- Hit proxy for first time (login) - begin polling.
- Stop your polling loop on the client, proxy poller is still running.
- Send to-device -> start polling with no `?pos=` set -> do you get it? Sounds like yes locally only.

**Comment by gnunicorn** [comment] 2022-10-24 11:47
I offer the:

1. Totally fresh local proxy
2. totally fresh local login for sliding-sync
3. first start against the local proxy - see's 0 pending to-device messages
```
sliding-sync-sliding-sync-1  |  github.com/matrix-org/sync-v3/cmd/syncv3/main.go:123 +0x10c5
sliding-sync-sliding-sync-1  | Sync v3 [0.5.2] (f6a482154f28cae2e73788204b41a730e052fc7f)
sliding-sync-sliding-sync-1  | 11:36:35 INF creating handler
sliding-sync-sliding-sync-1  | 11:36:35 INF retrieved global snapshot from database
sliding-sync-sliding-sync-1  | 11:36:35 INF listening on 0.0.0.0:8008
sliding-sync-sliding-sync-1  | 11:36:35 INF StartV2Pollers num_devices=0
sliding-sync-sliding-sync-1  | 11:36:35 INF StartV2Pollers finished
sliding-sync-sliding-sync-1  | 11:37:45 INF EnsurePolling: new request user=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:37:45 INF EnsurePolling: request finished user=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:37:45 INF EnsurePolling lock acquired device=f325848532b0919714a3945a6422dfefc4e86aa0a5c966ae04dff69526c4ad53 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:37:45 INF Poller: v2 poll loop started since= user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:39:13 INF Poller: valid initial sync response received user_id=@gnunicorn:matrix.org
qsliding-sync-sliding-sync-1  | 11:39:26 INF Poller: accumulated data rooms [invite,join,leave]=[0,150,0] storage [states,timelines,typing]=[150,150,51] to_device=0 user_id=@gnunicorn:matrix.org
```
4. content of the sliding-sync response, see's 0 pending to-device messages.
5. sending message via httpie. Client sees it - proxy does not report sending it.
```
│13:40:56:DEBUG:matrix_sdk_base::sliding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:228:ready to submit changes to store                      │
 │13:40:56:DEBUG:matrix_sdk_base::sliding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:232:applied changes                                       │
 │13:40:56:TRACE:matrix_sdk_base::sliding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:48:2 ToDevice Events found                                │
 │13:40:56:DEBUG:matrix_sdk_base::sliding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:228:ready to submit changes to store                      │
 │13:40:56:DEBUG:matrix_sdk_base::sliding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:232:applied changes  
```
Proxy:
```
sliding-sync-sliding-sync-1  | 11:40:56 INF  duration=10001.106336 p=20 q=21 r=0 size=157 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:40:56 INF  duration=0.151767 p=20 q=21 r=0 size=157 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:40:56 INF  d=2 duration=2.676434 p=21 q=22 r=0 size=1777 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:40:58 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:40:59 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:40:59 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:07 INF  duration=10001.866494 p=22 q=23 r=0 size=157 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:07 INF  duration=0.144705 p=22 q=23 r=0 size=157 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:09 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:09 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:10 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,0] to_device=0 user_id=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:17 INF  duration=10001.076636 p=23 q=24 r=0 size=157 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:17 INF  duration=0.230116 p=23 q=24 r=0 size=157 status=200 u=@gnunicorn:matrix.org
sliding-sync-sliding-sync-1  | 11:41:19 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
```


6. shutting down client. sending message. wait 2s. starting client with new login: `liding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:48:0 ToDevice Events found `
7. shutting down client. sending message. wait 2s. start client with existing login:
```
base::sliding_sync:crates/matrix-sdk-base/src/sliding_sync.rs:48:0 ToDevice Events found
```
8. keep client running, sending message: `rc/sliding_sync.rs:48:1 ToDevice Events found  `


With the proxy kept running, all local. On remote, as said, we don't see any to-device make it through, no matter if fresh or old login.

**Comment by kegsay** [comment] 2022-10-24 11:55
> proxy does not report sending it.

The cryptic keys do report 2 to-device messages sent from the proxy to the client:

```
11:40:56 INF  d=2 duration=2.676434 p=21 q=22 r=0 size=1777 status=200 u=@gnunicorn:matrix.org
```
`d` is the number of to-device events, `p` and `q` are the sent/next positions, `r` is the number of rooms in the top-level rooms JSON, `u` is the user. There's a bunch more as well for device list changes, etc.

So it sounds like everything works fine locally then? Is that correct?

**Comment by gnunicorn** [comment] 2022-10-24 12:05
ah, okay. that was non-obvious. I was looking at this, which never turns non `0`:
```
sliding-sync-sliding-sync-1  | 11:41:09 INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org
```

> So it sounds like everything works fine locally then? Is that correct?

I am not clear for how long to-device messages are meant to be held by sync before discarding them - so if we aren't connected, we don't see them. But I guess that is correct? Then yes, locally, it seems to work fine.

**Comment by kegsay** [comment] 2022-10-24 12:13
> I am not clear for how long to-device messages are meant to be held by sync before discarding them

Indefinitely as they may contain keys.

> so if we aren't connected, we don't see them. 

You should see them, assuming Synapse gives them to us.

`INF Poller: accumulated data rooms [invite,join,leave]=[0,1,0] storage [states,timelines,typing]=[0,0,1] to_device=0 user_id=@gnunicorn:matrix.org` is what the proxy received from the normal `/sync` request, so it never received to_device events.

**Comment by poljar** [comment] 2022-10-24 12:43
> I am not clear for how long to-device messages are meant to be held by sync before discarding them - so if we aren't connected, we don't see them. But I guess that is correct? Then yes, locally, it seems to work fine.

They are kept in the inbox until the Client confirms that it has received the sync response containing them. In other words, once the client uses the `next_batch` token that was received in the sync response containing a given to-device message, the server can discard the to-device event.

**Comment by kegsay** [comment] 2022-10-24 16:57
Regression tests added in https://github.com/matrix-org/sliding-sync/commit/52648b000f0c4ba34ea71cca66ba9ae7a247c3e8 (note sad red X)
Fixed in https://github.com/matrix-org/sliding-sync/commit/59f67d9b6a0bb726ca304c91c356425857c8eacc (note green tick)

Thanks for the detailed report and prompt feedback, as this really helped me nail down the issue!

**Closed by kegsay** 2022-10-24 16:57 UTC
Labels: bug, major
