### ISSUE TITLE
Define and support a single "merged output list" mode

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/sliding-sync#82] opened 2023-04-25 11:17 UTC
(or more generally: Decouple output lists from input lists?)

As alluded to in https://github.com/matrix-org/sliding-sync/issues/78:

> However: we have informally discussed a mode of operation where the client requests multiple lists and sends an additional flag, asking that the sync responses merge these lists into one output list. (This would apparently be useful for mobile clients.)
>
> [...] In this situation it's also possible that a room appears in multiple lists; we'd need to have well-defined semantics.

**Comment by kegsay** [comment] 2023-06-02 10:53
The reason for this issue is to enable the kinds of UX EX wants to support, specifically considering the kinds of ways to bump a room:

- DM rooms should bump for membership changes and reactions.
- Public rooms should not bump for membership changes and reactions.
- Muted rooms should only bump for a direct @mention.

To implement this today, you need 3 lists:
 - A DM list `is_dm: true` without `bump_event_types` being set.
 - A normal public list `is_dm: false` with `bump_event_types` set to `m.room.message` and `m.room.encrypted`.
 - There is no concept of `is_muted: true` in SS yet to filter muted rooms. There is no concept for `bump_event_types: [ "@mention" ]` or equiv. Let's assume this exists for this thought experiment.

Assuming all 3 lists are made, the problem is _how do you mix the lists together_ on the client? SS was originally designed for the EW UX which has Invites, People, and Rooms as _separate lists_. EX UX wants to combine these lists into one. This is where the idea of "merging multiple lists together" came from and is what this issue is about.

**Comment by kegsay** [comment] 2023-06-02 10:56
Conceptually, `bump_event_types` applies to all rooms in a single list. There is no way to say "for these kinds of rooms in this list, bump event types are X and for these other kinds of rooms in this list, bump event types are Y". If this existed, we could perhaps negate the need for the ability to merge lists. However, this would introduce a new model into the API (the idea of a subset of rooms in a list).

**Comment by pmaier1** [comment] 2023-06-02 12:18
**Notes from meeting today**

- requirements summary https://docs.google.com/document/d/1ryZjVuYBSfsu4e6fqYHIC9hJhY-aEWukcWMig1ewRA4/edit#heading=h.trije792g20r
- distinguish between messages and state events
- mixing of lists in backend agreed
- a room with the setting "notifications only for mentions/keywords" should not bump if there's no mention/keyword 
  - solve with one of the options in [intentional mentions mechanism](https://github.com/matrix-org/matrix-spec-proposals/pull/3996#discussion_r1201953906)?

**Comment by kegsay** [comment] 2023-07-12 18:03
Short conclusion: we can't do this fully in the server due to E2EE, therefore the client has to. As a result, there's nothing here for us to do, so closing.

**Closed by kegsay** 2023-07-12 18:03 UTC
Labels: roadmap
